apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ja0aukjuk-java-quarkus-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/ja0aukjuk-java-quarkus